### ISSUE TITLE
Generalized Procrustes Superimposition (GPS) details

### ISSUE THREAD

**Issue by habi** [habi/EAWAG-manuscript#5]
@kassthefish, in [line 93 of the materials & methods](https://github.com/habi/EAWAG-manuscript/blame/main/content/03.materials.methods.md#L93), I've copy-pasted your sentence as "This process brings all specimens to a common origin, scales centroid size, and rotates specimens to reduce distances between landmark sets."

My physicist brain cannot figure out what 'scales centroid size' means, as the centroid is a single point in my opinion.
Isn't this related to the common origin, e.g. the GPS brings all specimens to a common point, probably the centroid and scales/aligns them so their landmark sets are as close together as possible?

**Comment by kassthefish** [comment]
Here is an excerpt from the book: Geometric Morphometrics for Biologists.
I've read this book numerous times.
It describes the Procrustes Superimposition process:

"A step-wise description of the GLS method was presented by Rohlf (1990):
1. Center each configuration of landmarks at the origin by subtracting the coordinates of its centroid from the corresponding (X or Y) coordinates of each landmark. This translates each centroid to the origin (and the coordinates of the landmarks now reflect their deviation from the centroid).
2. Scale the landmark configurations to unit centroid size by dividing each coordinate of each landmark by the centroid size of that configuration.
3. Choose one configuration to be the reference, then rotate the second configuration to minimize the summed squared distances between homologous landmarks (over all landmarks) between the forms. In other words, rotate the second configuration to minimize the partial Procrustes distance."

Your confusion was the second step, where we try to remove "size" as an effect from the analysis.
Most morphologists are familiar with this process as it's pretty common in our work.
